services:
  - type: web
    name: vacaciones-app
    runtime: python
    repo: https://github.com/SebastianRamosSantiago/vacaciones-app
    plan: free
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true